apt install -y net-tools
apt install -y iptraf
apt install -y tzdata
apt install -y build-essential
apt install -y qt5-default
apt install -y libace-dev
apt install -y liblog4cxx-dev
apt install -y libboost-dev
apt install -y libboost-filesystem-dev
apt install -y libboost-program-options-dev
apt install -y libcpprest-dev
apt install -y libcurl4
apt install -y libcurl4-gnutls-dev
apt install -y libavcodec-dev
apt install -y libavformat-dev
apt install -y libavresample-dev
apt install -y libavutil-dev
apt install -y libswresample-dev
apt install -y libswscale-dev
apt install -y libavfilter-dev
apt install -y libavdevice-dev
apt install -y libtesseract-dev
apt install -y libtesseract4
apt install -y libopencv-dev
apt install -y libopencv-highgui-dev
apt install -y libopencv-imgproc-dev
apt install -y libopencv-video-dev
apt install -y libopencv-videoio-dev
apt install -y libopencv-imgcodecs-dev